# https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/templates/zshrc.zsh-template
export ZSH="/home/lixq/toolchains/ohmyzsh"
ZSH_THEME="ys"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# lixq
if [[ -x /home/lixq/toolchains/bat/usr/bin/bat ]]; then
    alias bat="/home/lixq/toolchains/bat/usr/bin/bat --paging=never"
elif command -v batcat >/dev/null 2>&1; then
    alias bat="batcat --paging=never"
else
    alias bat="cat"
fi
