# https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/templates/zshrc.zsh-template
export ZSH="/home/lixq/toolchains/oh-my-zsh"
ZSH_THEME="ys"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# lixq
if [[ -x /home/lixq/toolchains/bat/usr/bin/bat ]]; then
    alias bat="/home/lixq/toolchains/bat/usr/bin/bat --paging=never"
else
    alias bat="batcat --paging=never"
fi
